version: "3.7"

services:
  interview-testing:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    image: interview-testing/prod:latest
    restart: always
    command: yarn start:prod
    container_name: interview-testing
    environment:
      - "NODE_ENV=production"
    ports:
      - 6868:6868
