version: "3.7"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: testing_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  interview-testing:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    image: interview-testing/prod:latest
    restart: always
    command: yarn start:prod
    container_name: interview-testing
    environment:
      - "NODE_ENV=production"
    ports:
      - 6868:6868
    depends_on:
      - mongodb
